version: '3.8'

services:
  web:
    image: nginx:alpine
    user: 0:1000
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php
      - database

  php:
    build:
      dockerfile: ./docker/php/php-fpm.docker
      context: .
    working_dir: /var/www
    environment:
#      HOME: "/root"
      PHP_IDE_CONFIG: "serverName=DefaultHost"
    user: "1000:1000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - database

  database:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    user: 0:1000
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: talk
      MYSQL_USER: talk
      MYSQL_PASSWORD: password
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data:
